// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fdb07ae8-09d0-4c5b-b5c4-cfcf6f90dcdd";

const char SSID[]               = "Wokwi-GUEST";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = "ftoITW!ceZ3UVrQB@@eyxzuTi";    // Secret device password

void onAlarmStatusChange();

bool accessMode;
bool alarmStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(accessMode, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(alarmStatus, READWRITE, ON_CHANGE, onAlarmStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
